import './list_data.dart';

var tabooWords = [
  ListData("TASARRUF ETMEK", ["Para", "Zaman", "Daha sonra", "Banka"]),
  ListData("ÖDEMEK", ["Para", "Fiyat", "Fatura", "Satın almak", "Satmak"]),
  ListData("KAFA", ["Üst", "Yüz", "Yuvarlak", "Saç"]),
  ListData("KELİME", ["Yazmak", "Cümle", "Harf", "Konuşmak"]),
  ListData("Okumak", ["HECE", "Kelime", "Harf", "Ses", "Yazı"]),
  ListData("KÜSMEK", ["Darılmak", "Kızmak", "Konuşmak", "Tartışmak", "Kavga"]),
  ListData("AVİZE", ["Lamba", "Kristal", "Tavan", "Işık", "Aydınlık"]),
  ListData("KOORDİNAT", ["Yer", "Enlem", "Boylam", "Belirtmek", "Vermek"]),
  ListData("TERİM", ["Kelime", "Anlam", "Fatih", "Sanat", "Kavram"]),
  ListData("SOYUT", ["Duyu", "Algılamak", "Görülmeyen", "İsim", "Somut"]),
  ListData("BASKÜL", ["Tartı", "Kilo", "Ağır", "Ölçü", "Hafif"]),
  ListData("HALÜSİNASYON", ["Hayal", "Gerçek", "Görmek", "İllüzyon", "Serap"]),
  ListData(
      "ARMAĞAN", ["Hediye", "Vermek", "Almak", "Doğum günü", "Sevindirmek"]),
  ListData("ANTİKA", ["Müzayede", "Zengin", "Eski", "Tablo", "Tarihi"]),
  ListData("ADEM ELMASI", ["Erkek", "Gırtlak", "Çıkıntı", "Boğaz", "Havva"]),
  ListData("PLAKET", ["Ödül", "Tören", "Başarı", "Vermek", "Teşekkür"]),
  ListData("SATRANÇ", ["Şah-Mat", "Kale", "Vezir", "Piyon", "Fil"]),
  ListData("PARAŞÜT", ["Uçak", "Atlamak", "Uçmak", "Balon", "Hava"]),
  ListData("TİYATRO", ["Oyuncu", "Sahne", "Perde", "Oyun", "Suflör"]),
  ListData("DOST", ["Güven", "Samimi", "Dürüst", "Arkadaş", "Ahlaklı"]),
  ListData("ANAHTAR", ["Kilit", "Metal", "Kasa", "Kapı", "Çilingir"]),
  ListData("KEDİ", ["Pati", "Fare", "Tüy", "Kuyruk", "Hayvan"]),
  ListData(
      "BONKÖR", ["Eli Açık", "Cömert", "Para", "Gönlü Zengin", "Harcamak"]),
  ListData("FİDAN", ["Ağaç", "Büyümek", "Küçük", "Orman", "Dikmek"]),
  ListData("PRATİK", ["Kolay", "Zekâ", "Çabuk", "Hızlı", "Çözüm"]),
  ListData("MESAİ", ["Saat", "İş", "Fazla", "Akşam", "Kalmak"]),
  ListData("AKROSTİŞ", ["Şiir", "Mısra", "İsim", "İlk", "Kıta"]),
  ListData("BAMBU", ["Sazlık", "Panda", "Ağaç", "Masa", "Sandalye"]),
  ListData("YABANİ", ["Vahşi", "İlkel", "Hayat", "Orman", "Hayvan"]),
  ListData("YELPAZE", ["Sıcak", "Rüzgar", "Yaz", "Kadın", "Sallamak"]),
  ListData("ÇUVAL", ["Torba", "Doldurmak", "Yem", "Un", "Koymak"]),
  ListData("AJANDA", ["Plan", "Randevu", "Not", "Takvim", "Organize"]),
  ListData("İŞTAH", ["Acıkmak", "Kesilmek", "Açmak", "Lezzet", "Yemek"]),
  ListData("İHALE", ["Belediye", "Girmek", "Açmak", "Yolsuzluk", "Kazanmak"]),
  ListData("HİLE", ["Aldatmak", "Kandırmak", "Oyun", "Yapmak", "Kumar"]),
  ListData("HALAY", ["Düğün", "Çekmek", "Oynamak", "Mendil", "Mahmut Tuncer"]),
  ListData("STAJ", ["Öğrenci", "Çalışmak", "Üniversite", "Tecrübe", "İş"]),
  ListData("TECRÜBE", ["İş", "Kazanmak", "Çalışmak", "Deneyim", "Yıl"]),
  ListData("MACUN", ["Cam", "Pencere", "Tutmak", "Diş", "Mesir"]),
  ListData("MIZIKÇI", ["Çocuk", "Küsmek", "Darılmak", "Bozmak", "Oyun"]),
  ListData("ÇAVDAR", ["Arpa", "Tahıl", "Buğday", "Kepek", "Ekmek"]),
  ListData("VERESİYE", ["Peşin", "Borç", "Ödeme", "Hesap", "Defter"]),
  ListData("PERFORMANS", ["Değerlendirme", "Başarı", "Ders", "Ödev", "Yüksek"]),
  ListData("MONOTON", ["Aynı", "Sıkıcı", "Sıradan", "Benzer", "Rutin"]),
  ListData("PORSİYON", ["Yemek", "Tabak", "Lokanta", "Yarım", "Restoran"]),
  ListData("SERVET", ["Kazanmak", "Zenginlik", "Mal", "Mülk", "Para"]),
  ListData("TABURE", ["Oturak", "Ayak", "Yüksek", "Sandalye", "Masa"]),
  ListData("ÇAMAŞIR", ["Kirli", "Yıkamak", "Makine", "Deterjan", "Giymek"]),
  ListData("MİÇO", ["Tayfa", "Gemi", "Kaptan", "Deniz", "Yardımcı"]),
  ListData("ESKİMO", ["Kutup", "Buzul", "Kar", "Soğuk", "Balık"]),
  ListData("HASIR", ["Sepet", "Dokuma", "Plaj", "Deniz", "Sermek"]),
  ListData(
      "BUKALEMUN", ["Hayvan", "Renk", "Kertenkele", "Değişmek", "Sürüngen"]),
  ListData("KONVOY", ["Araba", "Gitmek", "Dizilmek", "Arka", "Düğün"]),
  ListData("VEZNE", ["Banka", "Para", "Ödeme", "Almak", "Muhasebe"]),
  ListData("CEPHE", ["Savaş", "Ordu", "Asker", "Saldırmak", "Barış"]),
  ListData("ZİRAAT", ["Tarım", "Çiftçi", "Toprak", "Hayvan", "Banka"]),
  ListData("FABL", ["Hayvan", "La Fontaine", "Masal", "İnsan", "Hikaye"]),
  ListData("MECAZ",
      ["Kelime", "Sözcük", "Gerçek Anlam", "Yan Anlam", "Terim Anlam"]),
  ListData("ÖZNE", ["Cümle", "İş", "Kişi", "Varlık", "Öge"]),
  ListData("FAY", ["Hat", "Deprem", "Kırılmak", "Sarsılmak", "İstanbul"]),
  ListData("VARSAYIM", ["Olmamış", "Tut ki", "Farz et", "Diyelim", "Cümle"]),
  ListData("PARAGRAF",
      ["Sınav", "Soru", "Ana düşünce", "Yardımcı düşünce", "Metin"]),
  ListData(
      "ÜÇ NOKTA", ["Noktalama", "Son", "Tamamlanmamış", "İstenmeyen", "Cümle"]),
  ListData("ŞATAFAT", ["Gösterişli", "Görkem", "İhtişam", "Çarpıcı", "Süs"]),
  ListData("ZAMİR", ["İsim", "Kişi", "Adıl", "İşaret", "Kelime"]),
  ListData("NOKTA", ["Son", "İşaret", "Tarih", "Cümle", "Saat"]),
  ListData("AHESTE", ["Yavaş", "Ağır", "Hızlı", "Tembel", "Durgun"]),
  ListData("PİL", ["Kalem", "İnce", "Kumanda", "El Feneri", "Fen"]),
  ListData(
      "PROSPEKTÜS", ["İlaç", "Eczane", "Okumak", "İçindekiler", "Kullanmak"]),
  ListData("ÇEVİK", ["Kuvvet", "Polis", "Asker", "Güç", "Hızlı"]),
  ListData("YAMAÇ", ["Uçurum", "Yüksek", "Dağ", "Dik", "Paraşüt"]),
  ListData("PAYLAŞMAK", ["Vermek", "Bölüşmek", "Zekat", "Fakir", "Zengin"]),
  ListData("KURBAN", ["Kesmek", "Allah", "Bayram", "Koç", "Hayvan"]),
  ListData("HAC", ["Kabe", "Tavaf", "Mekke", "İhram", "İbadet"]),
  ListData("SADAKA", ["Para", "Ömür", "Fakir", "Dilenci", "Yardım"]),
  ListData("ÇANTA", ["Omuz", "Taşımak", "Eşya", "Koymak", "Sırt"]),
  ListData("PUSULA", ["Kuzey", "Denizci", "Kaptan", "Yön", "Güney"]),
  ListData("PETROL", ["Otomobil", "Yakıt", "Akaryakıt", "Benzin", "Mazot"]),
  ListData("CİHAZ", ["Makine", "Ürün", "Aparat", "Küçük", "Elektronik"]),
  ListData("BETON", ["İnşaat", "Gri", "Duvar", "Yapmak", "Çimento"]),
  ListData("SERGİ", ["Dönem", "Okul", "Ders", "Fuar", "Sunmak"]),
  ListData("BİLİM", ["İnsan", "Yeni", "Laboratuvar", "Araştırma", "Deney"]),
  ListData("REKLAM", ["Yapmak", "Uygulama", "Televizyon", "Satış", "Para"]),
  ListData("GÜNEŞ", ["Parlak", "Sıcak", "Işık", "Gökyüzü", "Enerji"]),
  ListData("DENİZ", ["Mavi", "Dalga", "Kum", "Gemi", "Balık"]),
  ListData("KİTAP", ["Yazar", "Hikaye", "Sayfa", "Okumak", "Kütüphane"]),
  ListData("BİSİKLET", ["Tekerlek", "Pedal", "Sürmek", "Hız", "Doğa"]),
  ListData("KAMERA", ["Fotoğraf", "Video", "Lens", "Çekim", "Dijital"]),
  ListData("KÜLTÜR", ["Sanat", "Miras", "Gelenek", "Dil", "Tarih"]),
  ListData("YILDIZ", ["Gökyüzü", "Parlak", "Uzay", "Gece", "Astronomi"]),
  ListData("MÜZİSYEN", ["Enstrüman", "Melodi", "Ses", "Konser", "Şarkı"]),
  ListData("GÖZLÜK", ["Görmek", "Lens", "Çerçeve", "Göz", "Moda"]),
  ListData("KUŞ", ["Kanat", "Tüy", "Ötüş", "Yuva", "Gökyüzü"]),
  ListData("BİSİKLET", ["Tekerlek", "Pedal", "Sürmek", "Hız", "Doğa"]),
  ListData("BİLGİSAYAR", ["Teknoloji", "Donanım", "Yazılım", "Ekran", "Mouse"]),
  ListData("MÜZİK", ["Nota", "Enstrüman", "Melodi", "Dinlemek", "Konser"]),
  ListData("FOTOĞRAF", ["Lens", "Kamera", "Çekim", "Portre", "Görüntü"]),
  ListData("GÖKYÜZÜ", ["Bulut", "Güneş", "Uçak", "Mavi", "Yıldız"]),
  ListData("YEMEK", ["Tarif", "Malzeme", "Pişirmek", "Lezzet", "Restoran"]),
  ListData("HİKAYE", ["Karakter", "Olay", "Anlatmak", "Roman", "Sürükleyici"]),
  ListData("RENK", ["Palet", "Ton", "Uyum", "Canlı", "Kırmızı"]),
  ListData("AY", ["Gece", "Gökyüzü", "Dolunay", "Yıldız", "Astronomi"]),
  ListData("GÖLGE", ["Işık", "Karanlık", "Siluet", "Aydınlatma", "Güneş"]),
  ListData("ÇİÇEK", ["Bahar", "Renk", "Koku", "Toprak", "Bahçe"]),
  ListData("DENİZATI", ["Okyanus", "Eşek", "Deniz", "Balık", "At"]),
  ListData("UÇAK", ["Gökyüzü", "Pilot", "Yolcu", "Kalkış", "Iniş"]),
  ListData("SAAT", ["Zaman", "Dakika", "Saniye", "Akrep", "Yelkovan"]),
  ListData("ŞEMSIYE", ["Güneş", "Yağmur", "Gölge", "Plaj", "Açmak"]),
  ListData("AĞAÇ", ["Dal", "Yaprak", "Kök", "Gövde", "Orman"]),
  ListData("AYAKKABI", ["Moda", "Topuk", "Bağcık", "Spor", "Deri"]),
  ListData("BALIK", ["Akvaryum", "Yüzgeç", "Pullar", "Olta", "Deniz"]),
  ListData("KALEM", ["Yazmak", "Kâğıt", "Mürekkep", "Silgi", "Defter"]),
  ListData("GÖZ", ["Yüz", "Görmek", "Renk", "Gözlük", "Kaş"]),
  ListData("KÜRE", ["Top", "Dünya", "Gökyüzü", "Yüzey", "Küresel"]),
  ListData("KURŞUN KALEM", ["Çizim", "Silgi", "Renkli", "Uç", "Kağıt"]),
  ListData("KAPI", ["Giriş", "Çıkış", "Anahtar", "Kilit", "Kol"]),
  ListData("TELEFON", ["Konuşmak", "Arama", "Ekran", "Şarj", "Mesaj"]),
  ListData("GÜLÜMSEME", ["Yüz", "Mutluluk", "İfade", "Diş", "Sıcaklık"]),
  ListData("GÜNEŞ GÖZLÜĞÜ", ["Sıcak", "Yaz", "Ölen", "Moda", "Koruma"]),
  ListData("KUŞKU", ["Şüphe", "İnanç", "Güvensizlik", "Endişe", "Soru"]),
  ListData("KİTAPLIK", ["Kitap", "Raflar", "Okuma", "Yazar", "Kütüphane"]),
  ListData("PİANO", ["Müzik", "Tuş", "Melodi", "Çalgı", "Klasik"]),
  ListData("GÖL", ["Su", "Deniz", "Balık", "Yüzme", "Doğa"]),
  ListData("GÜNEŞLENMEK", ["Plaj", "Güneş", "Deniz", "Tatil", "Bronzlaşmak"]),
  ListData("DÜŞÜNCE", ["Zihin", "Fikir", "Plan", "Mantık", "Kafada"]),
  ListData("YAZI", ["Kalem", "Mürekkep", "Yazmak", "El Yazısı", "Kitap"]),
  ListData("GÖKDENİZ", ["Yıldız", "Gökyüzü", "Evren", "Uzay", "Galaksi"]),
  ListData("HARİTA", ["Yer", "Kıta", "Navigasyon", "Şehir", "Yol"]),
  ListData("ZAMAN YOLCUSU",
      ["Geçmiş", "Gelecek", "Saat", "Zaman Makinesi", "Tarih"]),
  ListData("TAVLA", ["Zar", "Oyun", "Yenmek", "Mars", "Kapı"]),
  ListData(
      "GOOGLE", ["Arama Motoru", "Bilgisayar", "İnternet", "Site", "Sayfa"]),
  ListData("BILL GATES", ["Zengin", "Microsoft", "Para", "PC", "Windows"]),
  ListData("PARA", ["Kağıt", "Dolar", "Satınalma", "Ülke", "Kazanmak"]),
  ListData("ÇORAP", ["İnce", "Kaçmak", "Ten Rengi", "Parziyen", "Ayak"]),
  ListData("AŞK", ["Kalp", "Bayan%Erkek", "Tutku", "Kırmızı", "Seks"]),
  ListData("MOUSE", ["Fare", "Bilgisayar", "Klavye", "Tuş", "Klik"]),
  ListData("TAKVİM", ["Yıl", "Ay", "Hafta", "Gün", "Sayı"]),
  ListData("MÜCEVHER", ["Kadın", "Takı", "Altın", "Bilezik", "Kolye"]),
  ListData("OJE", ["Tırnak", "Renk", "Sürmek", "Aseton", "Manikür"]),
  ListData("ŞİMŞEK", ["Gökyüzü", "Yağmur", "Işık", "Thor", "Korku"]),
  ListData("ARABA", ["Sürücü", "Seyahat", "Hızlı", "Taşıma", "Yolculuk"]),
  ListData("ÖRDEK", ["Kuş", "Sarı", "Tavuk", "Vak Vak", "Yem"]),
  ListData("YUSUFÇUK", ["Kırmızı", "Kanatlar", "Böcek", "Uçmak", "Sinek"]),
  ListData("KAR TANESİ", ["Soğuk", "Kış", "Teoman", "Yağmur", "Geometri"]),
  ListData("AÇ", ["His", "Yemek", "Kahvaltı", "Öğün", "Yemek"]),
  ListData("YASTIK", ["Baş", "Uyumak", "Yumuşak", "Yatak", "Rahatlık"]),
  ListData("DANS", ["Ritim", "Müzik", "Eğlence", "Gösteri", "Hareket"]),
  ListData("GURUR", ["His", "Başarı", "Büyük", "Övünmek", "Alçakgönüllü"]),
  ListData("BATTANİYE", ["Sıcak", "Yatak", "Örtü", "Yumuşak", "Soğuk"]),
  ListData("SALYANGOZ", ["Yuvarlak", "Yavaş", "Sümük", "Ev", "Kabuklu"]),
  ListData("ŞANGAY", ["Çin", "Şehir", "Uzakdoğu", "Asya", "Japonya"]),
  ListData("FUTBOL", ["Top", "Dünya Kupası", "Oyun", "Stadyum", "Kaleci"]),
  ListData("PEYNİR", ["Süt", "Tuzlu", "Lor", "Ezine", "Kaşar"]),
  ListData(
      "DİNOZOR", ["Büyük", "Hayvan", "Nesli Tükenmiş", "Eskiden", "Sürüngen"]),
  ListData("JAPONYA", ["Ülke", "Asya", "Kiraz Çiçeği", "Sushi", "Tokyo"]),
  ListData("NEW YORK", ["Şehir", "Amerika", "Büyük Elma", "Özgürlük Heykeli"]),
  ListData("İSİM", ["Ad", "Soyad", "Kimlik", "Tanımlama", "Etiket"]),
  ListData(
      "FİİL", ["Süpürmek", "Taşımak", "Desteklemek", "Tutmak", "Kaldırmak"]),
  ListData("KONUŞMA", ["Ağız", "Dil", "Söz", "İfade", "İletişim"]),
  ListData("SIFAT", ["Tanımlayıcı", "Nitelik", "İsim", "Özellik", "Sözcük"]),
  ListData("KİŞİ", ["Öğrenci", "Doktor", "Sanatçı", "Sporcu", "Yazar"]),
  ListData("YER", ["Şehir", "Köy", "Deniz", "Orman", "Dağ"]),
  ListData(
      "SÜPÜRGE", ["Süpürmek", "Ahşap", "Toz", "Taşıma", "Havaya Kaldırmak"]),
  ListData("TAŞIMA", ["Taksi", "Araç", "Toplu Taşıma", "Ulaşım", "Ücret"]),
  ListData(
      "DESTEKLEMEK", ["Taşımak", "Tutmak", "Kaldırmak", "Yardım", "Dayanmak"]),
  ListData("ÇİÇEK", ["Tomurcuk", "Genç", "Bahar", "Açmak", "Gelişmek"]),
  ListData("CADI", ["Süpürge", "Yeşil", "Büyü", "Halloween", "Güçler"]),
  ListData("ÇATAL", ["Kaşık", "Bıçak", "Yemek", "Bölme", "İki dişli"]),
  ListData("HALKA", ["Sıra", "Kalabalık", "Geçit", "Flamalar", "Toplanmak"]),
  ListData("MODA", ["Trend", "Giyim", "Stil", "Tasarım", "Marka"]),
  ListData("ÇÖP KUTUSU", ["Atık", "Temizlik", "Varil", "Değersiz", "Harabe"]),
  ListData("ESKİ", ["Antik", "Geçmiş", "Tarihi", "Anılar", "Moda"]),
  ListData("DÜĞÜN", ["Gelinlik", "Damatlık", "Dans", "Nikah", "Eğlence"]),
  ListData("ÖZEL", ["Kişisel", "Gizli", "Ayrıcalıklı", "Benzersiz", "Mahrem"]),
  ListData("ÜNLÜ", ["Şöhretli", "Tanınmış", "Popüler", "Talisca", "Messi"]),
  ListData("ÇOCUKLAR", ["Oyun", "Okul", "Küçük", "Masal", "Sevimli"]),
  ListData("KANAT", ["Kuş", "Tavuk", "Uçmak", "Yemek", "Tüy"]),
  ListData("PİLOT", ["Uçmak", "Uçak", "Helikopter", "Adam", "Seyahat"]),
  ListData("AVUKAT", ["Tartışmak", "Savunmak", "Hukuk", "Müvekkil", "Suç"]),
  ListData("TİMSAH", ["Sürüngen", "Diş", "Yeşil", "Vahşi", "Gölet"]),
  ListData("KUAFÖR", ["Saç", "Kesim", "Stil", "Makas", "Boya"]),
  ListData("CÜZDAN", ["Deri", "Çanta", "Para", "Kadın", "Taşımak"]),
  ListData("PORTAKAL", ["Renk", "Meyve", "Sulu", "Narenciye", "Kırmızı"]),
  ListData("MAKYAJ", ["Yüz", "Maskara", "Ruj", "Kızlar", "Güzel"]),
  ListData("ÖZEL DERS", ["Öğretmen", "Eğitim", "Öğrenci", "Evde", "Ders"]),
  ListData("Endişe", ["Kaygı", "Korku", "Stres", "Rahatsızlık", "Huzursuzluk"]),
  ListData("BALTA", ["Viking", "Odun", "Kesme", "Ağaç", "Demir"]),
  ListData("SARAY", ["Kral", "Prens", "Tarih", "İhtişam", "Şato"]),
  ListData("KORKU", ["Ürküntü", "Dehşet", "Gece", "Film", "Seri Katil"]),
  ListData("BEYAZ", ["Renk", "Saf", "Kar", "Temiz", "Aydınlık"]),
  ListData("YORGUN", ["Bitkin", "Halsiz", "Zayıf", "Tükenmiş", "Çalışmak"]),
  ListData(
      "DİNLENMEK", ["Rahatlamak", "Uyumak", "Boş zaman", "Huzur", "Tatil"]),
  ListData("BASINÇ", ["Atmosfer", "Kuvvet", "Deniz", "Sıkışma", "Denizaltı"]),
  ListData("ALABALIK", ["Akarsu", "Tatlısu", "Balık", "Su", "Avlanma"]),
  ListData("ŞAMPUAN", ["Saç", "Temizlik", "Köpük", "Banyo", "Yıkanmak"]),
  ListData("KÖPRÜ", ["Yol", "Boğaz", "Bağlantı", "Deniz", "Ulaşım"]),
  ListData("DEVE", ["Kamburlar", "Çöl", "Sahra", "Nerem doğru", "Arabistan"]),
  ListData("SİGARA", ["Bağımlılık", "Duman", "Nikotin", "Sağlık", "Tütün"]),
  ListData("BİLEZİK", ["Takı", "Altın", "Elmas", "Gümüş", "Yüzük"]),
  ListData("FIRÇA", ["Tarak", "Saç", "Resim", "Temizlik", "Boya"]),
  ListData("lİSANS", ["Derece", "Eğitim", "Diploma", "Universite", "Akademik"]),
  ListData("BAĞIRMAK", ["Çığlık", "Yüksek", "Ses", "Çağırmak", "Korku"]),
  ListData("RADYO", ["Dinle", "Müzik", "Eski", "FM", "Televizyon"]),
  ListData("KİLİT", ["Anahtar", "Güvenlik", "Kasa", "Kapı", "Açmak"]),
  ListData("ARMUT", ["Elma", "Meyve", "Şekil", "Ağaç", "Ayı"]),
  ListData(
      "ZIPLAMAK", ["Sıçramak", "Yüksek", "Atlamak", "Hareket", "Hafiflik"]),
  ListData("Eldiven", ["El", "Soğuk", "Kış", "Doktor", "Kaleci"]),
  ListData("VİZE", ["Üniversite", "Orta dönem", "Sınav", "Yarı", "Final"]),
  ListData("TORNADO", ["Fırtına", "Rüzgar", "Hortum", "Felaket", "Kasırga"]),
  ListData("TEKERLEKLİ SANDALYE",
      ["Sakat", "Özürlü", "Stephan Hawking :)", "Yaşlı"]),
  ListData("CANVAR", ["Korkunç", "Van", "Uzaylı", "Zombi"]),
  ListData("SIVI", ["Şeffaf", "Akışkan", "Su", "İçecek", "Sıvazlama"]),
  ListData("PAPATYA", ["Beyaz", "Sarı", "Çiçek", "Bitki", "Tarla"]),
  ListData("GELENEK", ["Örf", "Adet", "Davranış", "Toplum", "Aile"]),
  ListData("PERDE", ["Dekor", "Pencere", "Işık", "Kumaş", "Gölge"]),
  ListData("ZALİM", ["Kötü", "Öfkeli", "Kindar", "Acı", "Ağrı"]),
  ListData("SÜT", ["Beyaz", "Sıvı", "İçmek", "Kemik", "İnek"]),
  ListData("GİTAR", ["Enstrüman", "Çalmak", "Teller", "Melodi", "Müzik"]),
  ListData("TEBEŞİR", ["Beyaz", "Toz", "Öğretmen", "Siyah tahta", "Silmek"]),
  ListData("ŞİŞE", ["Bebek", "Cam", "Meyve suyu", "Su", "Kapak"]),
  ListData("SANDALYE", ["Mobilya", "Oturma", "Ayak", "Tahta", "Oturak"]),
  ListData("MESAFE", ["Konum", "Uzaklık", "Uzunluk", "Mil", "Metre"]),
  ListData("YAŞLI", ["Eskimiş", "Tecrübeli", "Emekli", "Saç", "Beyaz"]),
  ListData("BALIK", ["Yüzmek", "Solungaç", "Nehir", "Deniz", "Olta"]),
  ListData("TREN", ["Demir", "Seyehat", "Ray", "Demiryolu", "Choo-Choo!!"]),
  ListData("İĞNE", ["İğne", "Samanlık", "Keskin", "Metal", "Dikiş"]),
  ListData("SEVİNÇ", ["Mutlu", "Kutlamak", "Heyecanlı", "Zevk", "Gülümseme"]),
  ListData("MAYMUN", ["Sallanmak", "Muz", "Hayvan", "İnsan", "Evrim"]),
  ListData("HAVAİ FİŞEK", ["Patlamak", "Gökyüzü", "Renkli", "Işık", "Kutlama"]),
  ListData("SUPERMAN", ["Uçmak", "Kahraman", "Spiderman", "Batman", "Uzay"]),
  ListData("KÖPEKBALIĞI", ["Okyanus", "Büyük", "Tehlikeli", "Vahşi", "Deniz"]),
  ListData("PENCERE", ["Perde", "Cam", "Ev", "Görüntü", "Çerçeve"]),
  ListData("ÖĞRENCİ", ["Okul", "Lise", "Eğitim", "Öğretmen", "Üniversite"]),
  ListData("KAHVE", ["Çay", "Latte", "İçmek", "Kafein", "Starbucks"]),
  ListData("ZİL", ["Çalmak", "Tenefüs", "Okul", "Kapı", "Ev"]),
  ListData("ALTIN", ["Değerli", "Demir", "Maden", "Takı", "Sarı"]),
  ListData("KIVILCIM", ["Alev", "Yanma", "Çakmak", "Sürtünme", "Ateş"]),
  ListData("Noel Baba", ["Hediye", "Yılbaşı", "Kuzey kutbu", "Geyik", "Elf"]),
];
