import './list_data.dart';

var tabooWords = [
  ListData("TASARRUF ETMEK", ["Para", "Zaman", "Daha sonra", "Banka"]),
  ListData("ÖDEMEK", ["Para", "Fiyat", "Satın almak", "Satmak"]),
  ListData("KAFA", ["Üst", "Yüz", "Yuvarlak", "Saç"]),
  ListData("KELİME", ["Yazmak", "Cümle", "Harf", "Konuşmak"]),
  //
  ListData("Okumak", ["HECE", "Kelime", "Harf", "Ses", "Yazı"]),
  ListData("KÜSMEK", ["Darılmak", "Kızmak", "Konuşmak", "Tartışmak", "Kavga"]),
  ListData("AVİZE", ["Lamba", "Kristal", "Tavan", "Işık", "Aydınlık"]),
  ListData("KOORDİNAT", ["Yer", "Enlem", "Boylam", "Belirtmek", "Vermek"]),
  ListData("TERİM", ["Kelime", "Anlam", "Fatih", "Sanat", "Kavram"]),
  ListData("SOYUT", ["Duyu", "Algılamak", "Görülmeyen", "İsim", "Somut"]),
  ListData("BASKÜL", ["Tartı", "Kilo", "Ağır", "Ölçü", "Hafif"]),
  ListData("HALÜSİNASYON", ["Hayal", "Gerçek", "Görmek", "İllüzyon", "Serap"]),
  ListData(
      "ARMAĞAN", ["Hediye", "Vermek", "Almak", "Doğum günü", "Sevindirmek"]),
  ListData("ANTİKA", ["Müzayede", "Zengin", "Eski", "Tablo", "Tarihi"]),
  ListData("ADEM ELMASI", ["Erkek", "Gırtlak", "Çıkıntı", "Boğaz", "Havva"]),
  ListData("PLAKET", ["Ödül", "Tören", "Başarı", "Vermek", "Teşekkür"]),
  ListData("SATRANÇ", ["Şah-Mat", "Kale", "Vezir", "Piyon", "Fil"]),
  ListData("PARAŞÜT", ["Uçak", "Atlamak", "Uçmak", "Balon", "Hava"]),
  ListData("TİYATRO", ["Oyuncu", "Sahne", "Perde", "Oyun", "Suflör"]),
  ListData("DOST", ["Güven", "Samimi", "Dürüst", "Arkadaş", "Ahlaklı"]),
  ListData("ANAHTAR", ["Kilit", "Metal", "Kasa", "Kapı", "Çilingir"]),
  ListData("KEDİ", ["Pati", "Fare", "Tüy", "Kuyruk", "Hayvan"]),
  ListData(
      "BONKÖR", ["Eli Açık", "Cömert", "Para", "Gönlü Zengin", "Harcamak"]),
  ListData("FİDAN", ["Ağaç", "Büyümek", "Küçük", "Orman", "Dikmek"]),
  ListData("PRATİK", ["Kolay", "Zekâ", "Çabuk", "Hızlı", "Çözüm"]),
  ListData("MESAİ", ["Saat", "İş", "Fazla", "Akşam", "Kalmak"]),
  ListData("AKROSTİŞ", ["Şiir", "Mısra", "İsim", "İlk", "Kıta"]),
  ListData("BAMBU", ["Sazlık", "Mobilya", "Ağaç", "Masa", "Sandalye"]),
  ListData("YABANİ", ["Vahşi", "İlkel", "Hayat", "Orman", "Hayvan"]),
  ListData("YELPAZE", ["Sıcak", "Rüzgar", "Yaz", "Kadın", "Sallamak"]),
  ListData("ÇUVAL", ["Torba", "Doldurmak", "Yem", "Un", "Koymak"]),
  ListData("AJANDA", ["Defter", "İş", "Yazmak", "Gün", "Toplantı"]),
  ListData("İŞTAH", ["Acıkmak", "Kesilmek", "Açmak", "Lezzet", "Yemek"]),
  ListData("İHALE", ["Belediye", "Girmek", "Açmak", "Yolsuzluk", "Kazanmak"]),
  ListData("HİLE", ["Aldatmak", "Kandırmak", "Oyun", "Yapmak", "Kumar"]),
  ListData("HALAY", ["Düğün", "Çekmek", "Oynamak", "Mendil", "Mahmut Tuncer"]),
  ListData("STAJ", ["Öğrenci", "Çalışmak", "Üniversite", "Tecrübe", "İş"]),
  ListData("TECRÜBE", ["İş", "Kazanmak", "Çalışmak", "Deneyim", "Yıl"]),
  ListData("MACUN", ["Cam", "Pencere", "Tutmak", "Diş", "Mesir"]),
  ListData("MIZIKÇI", ["Çocuk", "Küsmek", "Darılmak", "Bozmak", "Oyun"]),
  ListData("ÇAVDAR", ["Arpa", "Tahıl", "Buğday", "Kepek", "Ekmek"]),
  ListData("VERESİYE", ["Peşin", "Borç", "Satın Almak", "Ödemek", "Defter"]),
  ListData("PERFORMANS", ["Değerlendirme", "Başarı", "Ders", "Ödev", "Yüksek"]),
  ListData("MONOTON", ["Aynı", "Sıkıcı", "Sıradan", "Benzer", "Rutin"]),
  ListData("PORSİYON", ["Yemek", "Tabak", "Lokanta", "Yarım", "Restoran"]),
  ListData("SERVET", ["Kazanmak", "Zenginlik", "Mal", "Mülk", "Para"]),
  ListData("TABURE", ["Oturmak", "Sandalye", "Koltuk", "Yemekhane", "Sırt"]),
  ListData("ÇAMAŞIR", ["Kirli", "Yıkamak", "Makine", "Deterjan", "Giymek"]),
  ListData("MİÇO", ["Tayfa", "Gemi", "Kaptan", "Deniz", "Yardımcı"]),
  ListData("ESKİMO", ["Kutup", "Buzul", "Kar", "Soğuk", "Balık"]),
  ListData("HASIR", ["Sepet", "Şapka", "Plaj", "Deniz", "Sermek"]),
  ListData(
      "BUKALEMUN", ["Hayvan", "Renk", "Kertenkele", "Değişmek", "Sürüngen"]),
  ListData("KONVOY", ["Araba", "Gitmek", "Dizilmek", "Arka", "Düğün"]),
  ListData("VEZNE", ["Banka", "Para", "Ödeme", "Almak", "Muhasebe"]),
  ListData("CEPHE", ["Savaş", "Ordu", "Asker", "Saldırmak", "Barış"]),
  ListData("ZİRAAT", ["Tarım", "Çiftçi", "Toprak", "Hayvan", "Banka"]),
  ListData("FABL", ["Hayvan", "La Fontaine", "Masal", "İnsan", "Hikaye"]),
  ListData("MECAZ",
      ["Kelime", "Sözcük", "Gerçek Anlam", "Yan Anlam", "Terim Anlam"]),
  ListData("ÖZNE", ["Cümle", "İş", "Kişi", "Varlık", "Öge"]),
  ListData("FAY", ["Hat", "Deprem", "Kırılmak", "Sarsılmak", "İstanbul"]),
  ListData("VARSAYIM", ["Olmamış", "Tut ki", "Farz et", "Diyelim", "Cümle"]),
  ListData("PARAGRAF",
      ["Sınav", "Soru", "Ana düşünce", "Yardımcı düşünce", "Metin"]),
  ListData(
      "ÜÇ NOKTA", ["Noktalama", "Son", "Tamamlanmamış", "İstenmeyen", "Cümle"]),
  ListData("ŞATAFAT", ["Gösterişli", "Görkem", "İhtişam", "Çarpıcı", "Süs"]),
  ListData("ZAMİR", ["İsim", "Kişi", "Adıl", "İşaret", "Kelime"]),
  ListData("NOKTA", ["Son", "İşaret", "Tarih", "Cümle", "Saat"]),
  ListData("AHESTE", ["Yavaş", "Ağır", "Hızlı", "Tembel", "Durgun"]),
  ListData("PİL", ["Kalem", "İnce", "Kumanda", "El Feneri", "Fen"]),
  ListData(
      "PROSPEKTÜS", ["İlaç", "Eczane", "Okumak", "İçindekiler", "Kullanmak"]),
  ListData("ÇEVİK", ["Kuvvet", "Polis", "Asker", "Güç", "Hızlı"]),
  ListData("YAMAÇ", ["Uçurum", "Yüksek", "Dağ", "Dik", "Paraşüt"]),
  ListData("PAYLAŞMAK", ["Vermek", "Bölüşmek", "Zekat", "Fakir", "Zengin"]),
  ListData("KURBAN", ["Kesmek", "Allah", "Bayram", "Koç", "Hayvan"]),
  ListData("HAC", ["Kabe", "Tavaf", "Mekke", "İhram", "İbadet"]),
  ListData("SADAKA", ["Para", "Ömür", "Fakir", "Dilenci", "Yardım"]),
  ListData("ÇANTA", ["Taşımak", "Yanında", "Eşya", "Koymak", "Pusula"]),
  ListData("PUSULA", ["Bilim", "Denizcilik", "Kaptan", "Gemi", "Yol"]),
  ListData("PETROL", ["Otomobil", "Yakıt", "Akaryakıt", "Benzin", "Mazot"]),
  ListData("CİHAZ", ["Makine", "Ürün", "Aparat", "Küçük", "Elektronik"]),
  ListData("BETON", ["İnşaat", "Gri", "Duvar", "Yapmak", "Çimento"]),
  ListData("SERGİ", ["Dönem", "Okul", "Ders", "Fuar", "Sunmak"]),
  ListData("BİLİM", ["İnsan", "Yeni", "Laboratuvar", "Araştırma", "Deney"]),
  ListData("REKLAM", ["Yapmak", "Uygulama", "Televizyon", "Satış", "Para"]),
  ListData("GÜNEŞ", ["Parlak", "Sıcak", "Işık", "Gökyüzü", "Enerji"]),
  ListData("DENİZ", ["Mavi", "Dalga", "Kum", "Gemi", "Balık"]),
  ListData("KİTAP", ["Yazar", "Hikaye", "Sayfa", "Okumak", "Kütüphane"]),
  ListData("BİSİKLET", ["Tekerlek", "Pedal", "Sürmek", "Hız", "Doğa"]),
  ListData("KAMERA", ["Fotoğraf", "Video", "Lens", "Çekim", "Dijital"]),
  ListData("KÜLTÜR", ["Sanat", "Miras", "Gelenek", "Dil", "Tarih"]),
  ListData("YILDIZ", ["Gökyüzü", "Parlak", "Uzay", "Gece", "Astronomi"]),
  ListData("MÜZİSYEN", ["Enstrüman", "Melodi", "Ses", "Konser", "Şarkı"]),
  ListData("GÖZLÜK", ["Görmek", "Lens", "Çerçeve", "Göz", "Moda"]),
  ListData("KUŞ", ["Kanat", "Tüy", "Ötüş", "Yuva", "Gökyüzü"]),
  ListData("BİSİKLET", ["Tekerlek", "Pedal", "Sürmek", "Hız", "Doğa"]),
  ListData("BİLGİSAYAR", ["Teknoloji", "Donanım", "Yazılım", "Ekran", "Mouse"]),
  ListData("MÜZİK", ["Nota", "Enstrüman", "Melodi", "Dinlemek", "Konser"]),
  ListData("FOTOĞRAF", ["Lens", "Kamera", "Çekim", "Portre", "Görüntü"]),
  ListData("GÖKYÜZÜ", ["Bulut", "Güneş", "Uçak", "Mavi", "Yıldız"]),
  ListData("YEMEK", ["Tarif", "Malzeme", "Pişirmek", "Lezzet", "Restoran"]),
  ListData("HİKAYE", ["Karakter", "Olay", "Anlatmak", "Roman", "Sürükleyici"]),
  ListData("RENK", ["Palet", "Ton", "Uyum", "Canlı", "Spectrum"]),
  ListData("AY", ["Gece", "Gökyüzü", "Dolunay", "Yıldız", "Astronomi"]),
  ListData("GÖLGE", ["Işık", "Karartmak", "Siluet", "Gölgeleme", "Güneş"]),
  ListData("ÇİÇEK", ["Bahar", "Renk", "Koku", "Toprak", "Bahçe"]),
  ListData(
      "DENİZATI", ["Mercan", "Balina", "Denizyıldızı", "Mercan", "Sualtı"]),
  ListData("UÇAK", ["Gökyüzü", "Pilot", "Yolcu", "Kalkış", "Iniş"]),
  ListData("SAAT", ["Zaman", "Dakika", "Saniye", "Akrep", "Yelkovan"]),
  ListData("ŞEMSIYE", ["Güneş", "Yağmur", "Gölge", "Plaj", "Açmak"]),
  ListData("AĞAÇ", ["Dal", "Yaprak", "Kök", "Gövde", "Orman"]),
  ListData("AYAKKABI", ["Moda", "Topuk", "Rahat", "Spor", "Deri"]),
  ListData("BALIK", ["Akvaryum", "Yüzgeç", "Pullar", "Akarsu", "Deniz"]),
  ListData("KALEM", ["Yazmak", "Kâğıt", "Mürekkep", "Silgi", "Defter"]),
  ListData("GÖZ", ["Görme", "Işık", "Renk", "Gözlük", "Kaş"]),
  ListData("KÜRE", ["Top", "Dünya", "Gökyüzü", "Yüzey", "Küresel"]),
  ListData("KURŞUN KALEM", ["Çizim", "Silgi", "Renkli", "Uç", "Kağıt"]),
  ListData("KAPI", ["Giriş", "Çıkış", "Mobilya", "Odun", "Kol"]),
  ListData("TELEFON", ["Konuşmak", "Mesaj", "Çağrı", "Ekran", "Şarj"]),
  ListData("GÜLÜMSEME", ["Yüz", "Mutluluk", "İfade", "Diş", "Sıcaklık"]),
  ListData("GÜNEŞ GÖZLÜĞÜ", ["Göz", "Güneş", "Gözlük", "Moda", "Koruma"]),
  ListData("KUŞKU", ["Şüphe", "İnanç", "Güvensizlik", "Endişe", "Soru"]),
  ListData("KİTAPLIK", ["Kitap", "Raflar", "Okuma", "Yazar", "Kütüphane"]),
  ListData("PİANO", ["Müzik", "Tuş", "Melodi", "Çalgı", "Klasik"]),
  ListData("GÖL", ["Su", "Kıyı", "Balık", "Ayna", "Doğa"]),
  ListData("GÜNEŞLENMEK", ["Plaj", "Güneş", "Deniz", "Tatil", "Bronzlaşmak"]),
  ListData("DÜŞÜNCE", ["Zihin", "Fikir", "Plan", "Mantık", "Kafada"]),
  ListData("YAZI", ["Kalem", "Mürekkep", "Yazmak", "El Yazısı", "Kitap"]),
  ListData("GÖKDENİZ", ["Yıldız", "Gökyüzü", "Evren", "Uzay", "Galaksi"]),
  ListData("HARİTA", ["Yer", "Rotası", "Şehir", "Ülke", "Yol"]),
];
